// 
//  MobileDataInterfaces.swift
//  SPHTech-Assignment
//
//  Created by Canh Tran Wizeline on 4/21/20.
//  Copyright © 2020 Canh Tran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
protocol MobileDataDependencyInterface {
    func makeMobileDataView() -> ViewInterface
}

// Router
protocol MobileDataRouterInterface: NavigationRouterInterface {
}

// ViewController
protocol MobileDataViewInterface: ViewInterface {
}

// Presenter
protocol MobileDataPresenterInterface: PresenterInterface {
}

// Interactor
protocol MobileDataInteractorInterface {
}
