// 
//  MobileDataRouter.swift
//  SPHTech-Assignment
//
//  Created by Canh Tran Wizeline on 4/21/20.
//  Copyright © 2020 Canh Tran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MobileDataRouter: NavigationRouter {
}

// MARK: - MobileDataRouterInterface

extension MobileDataRouter: MobileDataRouterInterface {
}
