// 
//  MobileDataInterfaces.swift
//  SPHTech-Assignment
//
//  Created by Canh Tran Wizeline on 4/21/20.
//  Copyright © 2020 Canh Tran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

// Dependency
public protocol MobileDataDependencyInterface {
    func makeMobileDataView() -> ViewInterface
}

// Router
public protocol MobileDataRouterInterface: NavigationRouterInterface {
}

// ViewController
public protocol MobileDataViewInterface: ViewInterface {
}

// Presenter
public protocol MobileDataPresenterInterface: PresenterInterface {
}

// Interactor
public protocol MobileDataInteractorInterface {
}
