// 
//  MobileDataViewController.swift
//  SPHTech-Assignment
//
//  Created by Canh Tran Wizeline on 4/21/20.
//  Copyright © 2020 Canh Tran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class MobileDataViewController: BaseViewController {
    // MARK: - Public Properties

    var presenter: MobileDataPresenterInterface!

    // MARK: - LifeCycle

    override func viewDidLoad() {
        super.viewDidLoad()
        setupView()
        presenter.viewDidLoad()
    }

    // MARK: - Setup

    private func setupView() {
        preferLargeTitleNavigationBar(enable: true, with: "Mobile Data 2008 - 2018")
    }
}

// MARK: - MobileDataViewInterface

extension MobileDataViewController: MobileDataViewInterface {
}
