// 
//  MobileDataPresenter.swift
//  SPHTech-Assignment
//
//  Created by Canh Tran Wizeline on 4/21/20.
//  Copyright © 2020 Canh Tran. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class MobileDataPresenter {
    // MARK: - Private Properties

    private unowned let view: MobileDataViewInterface
    private let interactor: MobileDataInteractorInterface
    private let router: MobileDataRouterInterface

    // MARK: - LifeCycle

    init(view: MobileDataViewInterface,
         interactor: MobileDataInteractorInterface,
         router: MobileDataRouterInterface) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

    func viewDidLoad() {
    }
}

// MARK: - MobileDataPresenterInterface

extension MobileDataPresenter: MobileDataPresenterInterface {
}
